### ISSUE TITLE
Add support for other LLMs that support Function Calling for `Langchain::Assistant` to work with

### ISSUE THREAD

**Issue by andreibondarev** [patterns-ai-core/langchainrb#543]
### Description
Currently OpenAI is the only supported LLM by `Langchain::Assistant`. We'd like to expand the list of support LLMs.

### Tasks
- [ ] Add support for Google Gemini (https://github.com/andreibondarev/langchainrb/pull/513)
- [ ] Add support for Cohere
- [ ] Add support for Anthropic
