### ISSUE TITLE
Add support for parallel_tool_calls option when configuring Langchain::Assistant

### ISSUE THREAD

**Issue by andreibondarev** [patterns-ai-core/langchainrb#813]
**Is your feature request related to a problem? Please describe.**
We'd like to enable better control of tool calling when using Langchain::Assistant. Some of the supported LLMs ([Anthropic](https://docs.anthropic.com/en/docs/build-with-claude/tool-use#disabling-parallel-tool-use) and [OpenAI](https://platform.openai.com/docs/api-reference/chat/create#chat-create-parallel_tool_calls)) let you modify whether parallel tool calls ("multiple tool calls") can be made or not. In some use-cases the Assistant **must** call tools sequentially hence we should be able to toggle that option on the Assistant instance.

**Describe the solution you'd like**
Similar to `tool_choice` enable the developer to toggle:
```ruby
assistant = Langchain::Assistant.new(parallel_tool_calls: true/false, ...)
assistant.parallel_tool_calls = true/false
```

#### Tasks
- [x] `Langchain::Assistant::LLM::Adapters::Anthropic` support
- [x] `Langchain::Assistant::LLM::Adapters::OpenAI` support
- [ ] `Langchain::Assistant::LLM::Adapters::GoogleGemini` support
- [ ] `Langchain::Assistant::LLM::Adapters::MistralAI` support
- [ ] `Langchain::Assistant::LLM::Adapters::Ollama` support

**Comment by sergiobayona** [comment]
I seems Google Gemini does support parallel function calling, see:

https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling#supported_models
https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling#parallel-samples

**Comment by andreibondarev** [comment]
> I seems Google Gemini does support parallel function calling, see:
> 
> https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling#supported_models https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling#parallel-samples

It does, but there's no way to configure whether functions can be called in parallel or not.

**Comment by ms-ati** [comment]
If we pass `parallel_tool_calls = false`, could we stop the debug output each time telling us that the adapter doesn't support parallel tool calls?

**Comment by andreibondarev** [comment]
> If we pass `parallel_tool_calls = false`, could we stop the debug output each time telling us that the adapter doesn't support parallel tool calls?

Have you tried changing the logger level? Something like `Langchain.logger.level = Logger::ERROR` should work.
